idf_component_register(
    SRCS
        "app_main.c"
        "hid_device.c"
        "net_manager.c"
        "video_input.c"
        "web_server.c"
    INCLUDE_DIRS "."
    EMBED_TXTFILES
        "www/index.html"
        "www/kvm.html"
    REQUIRES
        esp_driver_cam
        esp_driver_i2c
        esp_driver_isp
        esp_driver_jpeg
        esp_eth
        esp_event
        esp_hw_support
        esp_http_server
        esp_netif
        esp_psram
        esp_timer
        json
        nvs_flash
        spi_flash
        esp_cam_sensor
        esp_tinyusb
)
