#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "agent_event_store.h"
#include "agent_task_runtime.h"
#include "agent_verifier.h"
#include "authorization.h"
#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Transport-neutral, device-owned Agent Task Service. */
#define SI_AGENT_TASK_GOAL_MAX_LEN 512U
#define SI_AGENT_TASK_CRITERIA_MAX_LEN 256U
#define SI_AGENT_TASK_SOURCE_ID_MAX_LEN 64U
#define SI_AGENT_TASK_IDEMPOTENCY_MAX_LEN 64U
#define SI_AGENT_TASK_PROFILE_MAX_LEN 24U
#define SI_AGENT_TASK_MODEL_MAX_LEN 80U
#define SI_AGENT_TASK_STEER_MAX_LEN 512U
#define SI_AGENT_TASK_PAGE_CONTEXT_MAX_LEN 2048U
#define SI_AGENT_TASK_TOOL_MAX_LEN 48U
#define SI_AGENT_TASK_REASON_CODE_MAX_LEN 64U
#define SI_AGENT_TASK_COMPLETION_ARTIFACT_MAX_BYTES (32U * 1024U)
#define SI_AGENT_TASK_QQ_AUTHORITY_CEILING \
    ((si_capability_set_t)(SI_CAPABILITY_OBSERVE | SI_CAPABILITY_AGENT_RUN))

typedef enum {
    SI_AGENT_TASK_ORIGIN_WEB = 0,
    SI_AGENT_TASK_ORIGIN_QQ,
    SI_AGENT_TASK_ORIGIN_MCP,
    SI_AGENT_TASK_ORIGIN_SYSTEM,
} si_agent_task_origin_t;

typedef enum {
    SI_AGENT_TASK_HISTORY_NONE = 0,
    SI_AGENT_TASK_HISTORY_SINGLE_TURN,
    SI_AGENT_TASK_HISTORY_THREAD,
} si_agent_task_history_policy_t;

/*
 * Completion criteria provenance is adapter-owned metadata, never inferred
 * from user/model text. OBSERVATION requires independent observer/manager
 * evidence. DELIVERABLE means the criterion is only that a bounded response
 * artifact was durably produced, so Artifact Store evidence may satisfy it.
 * Zero intentionally selects the conservative OBSERVATION default.
 */
typedef enum {
    SI_AGENT_TASK_CRITERIA_OBSERVATION = 0,
    SI_AGENT_TASK_CRITERIA_DELIVERABLE,
} si_agent_task_completion_criteria_kind_t;

/*
 * Authentication is adapter-attested metadata, never request content.
 * DEVICE_SESSION binds Web/MCP work to an auth_service session generation.
 * ADAPTER_DELEGATION reserves the same revocable contract for QQ and future
 * transports; execution must stay fail-closed until that adapter supplies a
 * live delegation resolver. SYSTEM is limited to device-local callers.
 */
typedef enum {
    SI_AGENT_TASK_AUTH_DEVICE_SESSION = 0,
    SI_AGENT_TASK_AUTH_ADAPTER_DELEGATION,
    SI_AGENT_TASK_AUTH_SYSTEM,
} si_agent_task_auth_kind_t;

typedef struct {
    si_agent_task_origin_t origin;
    const char *source_account_id;
    const char *source_conversation_id;
    const char *source_actor_id;
    const char *external_event_id;
    si_agent_task_auth_kind_t auth_kind;
    si_principal_kind_t principal;
    /* Opaque device-generated session/delegation ID; never an auth token. */
    const char *auth_id;
    uint32_t auth_generation;
    si_capability_set_t authority_ceiling;
    si_agent_task_history_policy_t history_policy;
} si_agent_task_source_t;

typedef struct {
    /* Trusted adapter-generated Thread ID; empty creates a new one. */
    const char *thread_id;
    /*
     * Optional device-owned correlation IDs. They are generated by the
     * in-firmware legacy executor adapter, never copied from transport JSON.
     * Supplying both lets the V2 shadow journal describe the exact legacy
     * run which the Request Broker will later bind. Supplying only one is
     * invalid.
     */
    const char *turn_id;
    const char *run_id;
    const char *goal;
    const char *completion_criteria;
    si_agent_task_completion_criteria_kind_t completion_criteria_kind;
    const char *idempotency_key;
    const char *profile;
    const char *model;
    const char *page_context_json;
    bool dry_run;
    bool include_screenshot;
    bool allow_web_search;
    si_agent_task_source_t source;
} si_agent_task_submit_t;

typedef struct {
    bool accepted;
    bool started;
    bool queued;
    bool deduplicated;
    size_t queue_position;
    char thread_id[SI_AGENT_TASK_ID_MAX + 1U];
    char turn_id[SI_AGENT_TASK_ID_MAX + 1U];
    char run_id[SI_AGENT_TASK_ID_MAX + 1U];
} si_agent_task_receipt_t;

/* Bounded execution projection; secrets and raw external IDs are excluded. */
typedef struct {
    bool used;
    char thread_id[SI_AGENT_TASK_ID_MAX + 1U];
    char turn_id[SI_AGENT_TASK_ID_MAX + 1U];
    char run_id[SI_AGENT_TASK_ID_MAX + 1U];
    char goal[SI_AGENT_TASK_GOAL_MAX_LEN + 1U];
    char completion_criteria[SI_AGENT_TASK_CRITERIA_MAX_LEN + 1U];
    si_agent_task_completion_criteria_kind_t completion_criteria_kind;
    char idempotency_key[SI_AGENT_TASK_IDEMPOTENCY_MAX_LEN + 1U];
    char profile[SI_AGENT_TASK_PROFILE_MAX_LEN + 1U];
    char model[SI_AGENT_TASK_MODEL_MAX_LEN + 1U];
    char page_context_json[SI_AGENT_TASK_PAGE_CONTEXT_MAX_LEN + 1U];
    si_agent_task_origin_t origin;
    si_agent_task_auth_kind_t auth_kind;
    si_principal_kind_t source_principal;
    char source_auth_id[SI_AGENT_TASK_SOURCE_ID_MAX_LEN + 1U];
    uint32_t source_auth_generation;
    si_capability_set_t authority_ceiling;
    si_agent_task_history_policy_t history_policy;
    bool dry_run;
    bool include_screenshot;
    bool allow_web_search;
    bool action_outcome_unknown;
} si_agent_task_execution_t;

typedef struct {
    bool available;
    bool storage_healthy;
    si_agent_event_recovery_status_t recovery_status;
    uint64_t latest_event_seq;
    size_t queue_depth;
    si_agent_task_runtime_t runtime;
    si_agent_task_execution_t active;
} si_agent_task_service_snapshot_t;

/*
 * Opaque-by-contract handle for one final-response artifact that TASKS.LOG has
 * already committed. Callers may carry this value between the record and
 * completion calls, but Task Service accepts it only when every field matches
 * the service-owned record created by the durable append. A caller-invented
 * verifier verdict or evidence object is never accepted.
 */
typedef struct {
    uint64_t event_seq;
    uint64_t captured_ms;
    uint64_t generation;
    uint32_t artifact_bytes;
    si_agent_evidence_kind_t kind;
    si_agent_evidence_issuer_t issuer;
    char artifact_id[SI_AGENT_VERIFY_ID_MAX_LEN + 1U];
    char artifact_hash[SI_AGENT_VERIFY_HASH_MAX_LEN + 1U];
    char action_id[SI_AGENT_VERIFY_ID_MAX_LEN + 1U];
    char target_identity[SI_AGENT_VERIFY_TARGET_MAX_LEN + 1U];
    char completion_criteria_hash[SI_AGENT_VERIFY_HASH_MAX_LEN + 1U];
    char event_hash[SI_AGENT_EVENT_HASH_HEX_LEN + 1U];
} si_agent_completion_artifact_t;

/* Allocates/publishes the service mutex only; performs no TF or replay I/O. */
esp_err_t si_agent_task_service_prepare(void);
/* Web startup reserves recovery before it begins accepting requests. */
esp_err_t si_agent_task_service_reserve_recovery(void);
esp_err_t si_agent_task_service_recover_reserved(void);
esp_err_t si_agent_task_service_start(void);

esp_err_t si_agent_task_service_submit(const si_agent_task_submit_t *input,
                                       si_agent_task_receipt_t *receipt);

esp_err_t si_agent_task_service_snapshot(
    si_agent_task_service_snapshot_t *snapshot);

esp_err_t si_agent_task_service_get_execution(
    const char *run_id, si_agent_task_execution_t *execution);

/* Lifecycle mutations are journaled before they become visible in memory. */
esp_err_t si_agent_task_service_set_phase(
    const char *run_id, si_agent_turn_status_t phase);
esp_err_t si_agent_task_service_begin_plan(const char *run_id,
                                           const char *plan_id);
esp_err_t si_agent_task_service_add_step(const char *run_id,
                                         const char *step_id);
esp_err_t si_agent_task_service_set_step_status(
    const char *run_id, const char *step_id, si_agent_step_status_t status);
esp_err_t si_agent_task_service_record_step_verification(
    const char *run_id, const char *step_id,
    si_agent_verification_status_t verification,
    const char *evidence_id);
esp_err_t si_agent_task_service_record_turn_verification(
    const char *run_id, si_agent_verification_status_t verification,
    const char *evidence_id);
/*
 * Only no-mutation final responses may enter this typed artifact path.
 * Recording proves response delivery only. Completion additionally requires
 * a durable adapter-owned DELIVERABLE criterion; OBSERVATION stays unverified.
 */
esp_err_t si_agent_task_service_record_readonly_completion_artifact(
    const char *run_id, const char *step_id, const char *artifact_hash,
    uint32_t artifact_bytes, si_agent_completion_artifact_t *artifact_out);
esp_err_t si_agent_task_service_complete_readonly(
    const char *run_id, const char *step_id,
    const si_agent_completion_artifact_t *artifact,
    si_agent_verification_result_t *verification_out);
/* Canonical side-effect ledger. STARTED must be durable before execution. */
esp_err_t si_agent_task_service_record_action_started(
    const char *run_id, const char *step_id, const char *action_id,
    const char *tool_name, const char *normalized_args_sha256,
    const char *idempotency_key, bool mutation);
esp_err_t si_agent_task_service_record_action_result(
    const char *run_id, const char *step_id, const char *action_id,
    bool succeeded, const char *artifact_id, const char *reason_code);
esp_err_t si_agent_task_service_steer(const char *run_id,
                                      const char *message);
esp_err_t si_agent_task_service_pause(const char *run_id);
esp_err_t si_agent_task_service_resume(const char *run_id);
esp_err_t si_agent_task_service_cancel(const char *run_id);
esp_err_t si_agent_task_service_interrupt(const char *run_id,
                                          const char *reason);
esp_err_t si_agent_task_service_mark_outcome_unknown(
    const char *run_id, const char *action_id, const char *reason);
esp_err_t si_agent_task_service_fail(const char *run_id,
                                     const char *reason);
esp_err_t si_agent_task_service_complete(const char *run_id);
esp_err_t si_agent_task_service_revoke_page_context(void);

/* Removes a terminal active Turn and promotes the oldest queued Turn. */
esp_err_t si_agent_task_service_advance(si_agent_task_execution_t *next,
                                        bool *started_out);

esp_err_t si_agent_task_service_replay(
    uint64_t after_seq, si_agent_event_replay_cb_t callback, void *user_ctx,
    si_agent_event_recovery_t *recovery_out);

const char *si_agent_task_origin_name(si_agent_task_origin_t origin);
const char *si_agent_task_auth_kind_name(si_agent_task_auth_kind_t kind);
const char *si_agent_task_history_policy_name(
    si_agent_task_history_policy_t policy);
const char *si_agent_task_service_last_error(void);

#ifdef __cplusplus
}
#endif
