#pragma once

#include <stdbool.h>
#include <stdint.h>

#include "board_config.h"
#include "sdkconfig.h"

#define SI_BMC_VERSION "0.86.0-stable-kvm"
#define SI_BMC_HOSTNAME CONFIG_SI_BOARD_HOSTNAME
#define SI_BMC_BOARD CONFIG_SI_BOARD_NAME

#define SI_STATUS_POLL_INTERVAL_MS 1000U
#define SI_DEFAULT_HTTP_PORT 80
#define SI_STREAM_HTTP_PORT 81

#ifndef CONFIG_SI_AUTH_USERNAME
#define CONFIG_SI_AUTH_USERNAME "admin"
#endif
#ifndef CONFIG_SI_AUTH_PASSWORD
#define CONFIG_SI_AUTH_PASSWORD ""
#endif
#ifndef CONFIG_SI_VIDEO_WIDTH
#define CONFIG_SI_VIDEO_WIDTH 1280
#endif
#ifndef CONFIG_SI_VIDEO_HEIGHT
#define CONFIG_SI_VIDEO_HEIGHT 720
#endif
#ifndef CONFIG_SI_VIDEO_UVC_FPS
#define CONFIG_SI_VIDEO_UVC_FPS 30
#endif
#ifndef CONFIG_SI_VIDEO_UVC_FRAME_BUFFERS
#define CONFIG_SI_VIDEO_UVC_FRAME_BUFFERS 3
#endif
#ifndef CONFIG_SI_VIDEO_UVC_URBS
#define CONFIG_SI_VIDEO_UVC_URBS 4
#endif
#ifndef CONFIG_SI_VIDEO_UVC_URB_SIZE
#define CONFIG_SI_VIDEO_UVC_URB_SIZE 16384
#endif
#ifndef CONFIG_SI_VIDEO_UVC_JPEG_BUFFER_SIZE
#define CONFIG_SI_VIDEO_UVC_JPEG_BUFFER_SIZE (1024 * 1024)
#endif
#ifndef CONFIG_SI_VIDEO_JPEG_QUALITY
#define CONFIG_SI_VIDEO_JPEG_QUALITY 75
#endif
#ifndef CONFIG_SI_VIDEO_STREAM_DELAY_MS
#define CONFIG_SI_VIDEO_STREAM_DELAY_MS 33
#endif

#define SI_CFG_AUTH_USERNAME CONFIG_SI_AUTH_USERNAME
#define SI_CFG_AUTH_PASSWORD CONFIG_SI_AUTH_PASSWORD

_Static_assert(sizeof(SI_CFG_AUTH_PASSWORD) >= 7,
               "Set a unique CONFIG_SI_AUTH_PASSWORD (minimum 6 characters) in the local sdkconfig");

#ifdef CONFIG_SI_VIDEO_ENABLE
#define SI_CFG_VIDEO_ENABLED 1
#else
#define SI_CFG_VIDEO_ENABLED 0
#endif

#define SI_CFG_VIDEO_WIDTH CONFIG_SI_VIDEO_WIDTH
#define SI_CFG_VIDEO_HEIGHT CONFIG_SI_VIDEO_HEIGHT
#define SI_CFG_VIDEO_FPS CONFIG_SI_VIDEO_UVC_FPS
#define SI_CFG_VIDEO_FRAME_BUFFERS CONFIG_SI_VIDEO_UVC_FRAME_BUFFERS
#define SI_CFG_VIDEO_URBS CONFIG_SI_VIDEO_UVC_URBS
#define SI_CFG_VIDEO_URB_SIZE CONFIG_SI_VIDEO_UVC_URB_SIZE
#define SI_CFG_VIDEO_JPEG_BUFFER_SIZE CONFIG_SI_VIDEO_UVC_JPEG_BUFFER_SIZE
#define SI_CFG_VIDEO_JPEG_QUALITY CONFIG_SI_VIDEO_JPEG_QUALITY
#define SI_CFG_VIDEO_STREAM_DELAY_MS CONFIG_SI_VIDEO_STREAM_DELAY_MS

static inline bool si_auth_enabled(void)
{
    return SI_CFG_AUTH_PASSWORD[0] != '\0';
}
