#pragma once

/*
 * Single compile-time view of the selected hardware profile.
 *
 * Board values are declared in Kconfig.projbuild and selected by an
 * sdkconfig.defaults profile. Drivers include this header instead of reading
 * CONFIG_* symbols or carrying private fallback GPIO values.
 */

#include "sdkconfig.h"
#include "esp_idf_version.h"

#define SI_BOARD_ID CONFIG_SI_BOARD_ID
#define SI_BOARD_NAME CONFIG_SI_BOARD_NAME
#define SI_BOARD_HOSTNAME CONFIG_SI_BOARD_HOSTNAME
#define SI_SILICON_TARGET CONFIG_SI_SILICON_TARGET
#define SI_CFG_ETH_PHY_NAME CONFIG_SI_ETH_PHY_NAME
#define SI_CFG_ETH_DRIVER_NAME CONFIG_SI_ETH_DRIVER_NAME

#if defined(CONFIG_SI_BOARD_REQUIRES_REV3) && defined(CONFIG_ESP32P4_SELECTS_REV_LESS_V3)
#error "The selected ExoAnchor prototype requires the esp32p4-rev3 silicon overlay"
#endif

#if defined(CONFIG_SI_BOARD_REQUIRES_REV3) && ESP_IDF_VERSION < ESP_IDF_VERSION_VAL(5, 5, 4)
#error "ESP32-P4 rev3 prototype profiles require ESP-IDF v5.5.4 or newer"
#endif

/* Disabled Kconfig menus may omit their dependent symbols from sdkconfig.h. */
#ifndef CONFIG_SI_ETH_MDC_GPIO
#define CONFIG_SI_ETH_MDC_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_MDIO_GPIO
#define CONFIG_SI_ETH_MDIO_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_PHY_RST_GPIO
#define CONFIG_SI_ETH_PHY_RST_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_PHY_ADDR
#define CONFIG_SI_ETH_PHY_ADDR -1
#endif
#ifndef CONFIG_SI_ETH_RMII_CLK_GPIO
#define CONFIG_SI_ETH_RMII_CLK_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_RMII_TX_EN_GPIO
#define CONFIG_SI_ETH_RMII_TX_EN_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_RMII_TXD0_GPIO
#define CONFIG_SI_ETH_RMII_TXD0_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_RMII_TXD1_GPIO
#define CONFIG_SI_ETH_RMII_TXD1_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_RMII_CRS_DV_GPIO
#define CONFIG_SI_ETH_RMII_CRS_DV_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_RMII_RXD0_GPIO
#define CONFIG_SI_ETH_RMII_RXD0_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_RMII_RXD1_GPIO
#define CONFIG_SI_ETH_RMII_RXD1_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_WAIT_IP_TIMEOUT_MS
#define CONFIG_SI_ETH_WAIT_IP_TIMEOUT_MS 0
#endif

#ifdef CONFIG_SI_ETH_ENABLE
#define SI_CFG_ETH_ENABLED 1
#else
#define SI_CFG_ETH_ENABLED 0
#endif

#define SI_CFG_ETH_MDC_GPIO CONFIG_SI_ETH_MDC_GPIO
#define SI_CFG_ETH_MDIO_GPIO CONFIG_SI_ETH_MDIO_GPIO
#define SI_CFG_ETH_PHY_RESET_GPIO CONFIG_SI_ETH_PHY_RST_GPIO
#define SI_CFG_ETH_PHY_ADDRESS CONFIG_SI_ETH_PHY_ADDR
#define SI_CFG_ETH_RMII_CLOCK_GPIO CONFIG_SI_ETH_RMII_CLK_GPIO
#define SI_CFG_ETH_RMII_TX_ENABLE_GPIO CONFIG_SI_ETH_RMII_TX_EN_GPIO
#define SI_CFG_ETH_RMII_TXD0_GPIO CONFIG_SI_ETH_RMII_TXD0_GPIO
#define SI_CFG_ETH_RMII_TXD1_GPIO CONFIG_SI_ETH_RMII_TXD1_GPIO
#define SI_CFG_ETH_RMII_CRS_DV_GPIO CONFIG_SI_ETH_RMII_CRS_DV_GPIO
#define SI_CFG_ETH_RMII_RXD0_GPIO CONFIG_SI_ETH_RMII_RXD0_GPIO
#define SI_CFG_ETH_RMII_RXD1_GPIO CONFIG_SI_ETH_RMII_RXD1_GPIO
#define SI_CFG_ETH_WAIT_IP_TIMEOUT_MS CONFIG_SI_ETH_WAIT_IP_TIMEOUT_MS

#ifndef CONFIG_SI_POWER_BUTTON_GPIO
#define CONFIG_SI_POWER_BUTTON_GPIO -1
#endif
#ifndef CONFIG_SI_RESET_BUTTON_GPIO
#define CONFIG_SI_RESET_BUTTON_GPIO -1
#endif
#ifndef CONFIG_SI_POWER_PRESS_MS
#define CONFIG_SI_POWER_PRESS_MS 500
#endif
#ifndef CONFIG_SI_POWER_FORCE_OFF_MS
#define CONFIG_SI_POWER_FORCE_OFF_MS 5000
#endif
#ifndef CONFIG_SI_POWER_DETECT_GPIO
#define CONFIG_SI_POWER_DETECT_GPIO -1
#endif
#ifndef CONFIG_SI_STANDBY_DETECT_GPIO
#define CONFIG_SI_STANDBY_DETECT_GPIO -1
#endif
#ifndef CONFIG_SI_POWER_RESERVE1_GPIO
#define CONFIG_SI_POWER_RESERVE1_GPIO -1
#endif
#ifndef CONFIG_SI_POWER_RESERVE2_GPIO
#define CONFIG_SI_POWER_RESERVE2_GPIO -1
#endif
#ifndef CONFIG_SI_POWER_RESERVE3_GPIO
#define CONFIG_SI_POWER_RESERVE3_GPIO -1
#endif
#ifndef CONFIG_SI_POWER_RESERVE4_GPIO
#define CONFIG_SI_POWER_RESERVE4_GPIO -1
#endif
#ifndef CONFIG_SI_POWER_LOCATOR_GPIO
#define CONFIG_SI_POWER_LOCATOR_GPIO -1
#endif

#ifdef CONFIG_SI_POWER_ENABLE
#define SI_CFG_POWER_ENABLED 1
#else
#define SI_CFG_POWER_ENABLED 0
#endif

#define SI_CFG_POWER_BUTTON_GPIO CONFIG_SI_POWER_BUTTON_GPIO
#define SI_CFG_RESET_BUTTON_GPIO CONFIG_SI_RESET_BUTTON_GPIO
#ifdef CONFIG_SI_POWER_ACTIVE_HIGH
#define SI_CFG_POWER_ACTIVE_HIGH 1
#else
#define SI_CFG_POWER_ACTIVE_HIGH 0
#endif
#define SI_CFG_POWER_PRESS_MS CONFIG_SI_POWER_PRESS_MS
#define SI_CFG_POWER_FORCE_OFF_MS CONFIG_SI_POWER_FORCE_OFF_MS
#define SI_CFG_POWER_DETECT_GPIO CONFIG_SI_POWER_DETECT_GPIO
#ifdef CONFIG_SI_POWER_DETECT_ACTIVE_HIGH
#define SI_CFG_POWER_DETECT_ACTIVE_HIGH 1
#else
#define SI_CFG_POWER_DETECT_ACTIVE_HIGH 0
#endif
#define SI_CFG_STANDBY_DETECT_GPIO CONFIG_SI_STANDBY_DETECT_GPIO
#ifdef CONFIG_SI_STANDBY_DETECT_ACTIVE_HIGH
#define SI_CFG_STANDBY_DETECT_ACTIVE_HIGH 1
#else
#define SI_CFG_STANDBY_DETECT_ACTIVE_HIGH 0
#endif
#define SI_CFG_POWER_RESERVE1_GPIO CONFIG_SI_POWER_RESERVE1_GPIO
#define SI_CFG_POWER_RESERVE2_GPIO CONFIG_SI_POWER_RESERVE2_GPIO
#define SI_CFG_POWER_RESERVE3_GPIO CONFIG_SI_POWER_RESERVE3_GPIO
#define SI_CFG_POWER_RESERVE4_GPIO CONFIG_SI_POWER_RESERVE4_GPIO
#define SI_CFG_POWER_LOCATOR_GPIO CONFIG_SI_POWER_LOCATOR_GPIO
#ifdef CONFIG_SI_POWER_LOCATOR_ACTIVE_HIGH
#define SI_CFG_POWER_LOCATOR_ACTIVE_HIGH 1
#else
#define SI_CFG_POWER_LOCATOR_ACTIVE_HIGH 0
#endif

#ifndef CONFIG_SI_HID_USB_DM_GPIO
#define CONFIG_SI_HID_USB_DM_GPIO -1
#endif
#ifndef CONFIG_SI_HID_USB_DP_GPIO
#define CONFIG_SI_HID_USB_DP_GPIO -1
#endif
#ifndef CONFIG_SI_HID_USB_MANUFACTURER
#define CONFIG_SI_HID_USB_MANUFACTURER "ExoAnchor"
#endif
#ifndef CONFIG_SI_HID_USB_PRODUCT
#define CONFIG_SI_HID_USB_PRODUCT "ESP32-P4 USB HID"
#endif
#ifndef CONFIG_SI_HID_USB_SERIAL
#define CONFIG_SI_HID_USB_SERIAL "P4-FS-HID"
#endif

#ifdef CONFIG_SI_HID_USB_ENABLE
#define SI_CFG_HID_ENABLED 1
#else
#define SI_CFG_HID_ENABLED 0
#endif

#define SI_CFG_HID_DM_GPIO CONFIG_SI_HID_USB_DM_GPIO
#define SI_CFG_HID_DP_GPIO CONFIG_SI_HID_USB_DP_GPIO
#define SI_CFG_HID_MANUFACTURER CONFIG_SI_HID_USB_MANUFACTURER
#define SI_CFG_HID_PRODUCT CONFIG_SI_HID_USB_PRODUCT
#define SI_CFG_HID_SERIAL CONFIG_SI_HID_USB_SERIAL
