#pragma once

#include <stdbool.h>
#include <stdint.h>

#include "board_config.h"
#include "sdkconfig.h"

#ifndef SI_BMC_VERSION
#define SI_BMC_VERSION "0.87.6-dev"
#endif
#define SI_BMC_HOSTNAME CONFIG_SI_BOARD_HOSTNAME
#define SI_BMC_BOARD CONFIG_SI_BOARD_NAME

#ifdef CONFIG_SI_BUILD_PROFILE_STABLE
#define SI_BUILD_PROFILE "stable"
#else
#define SI_BUILD_PROFILE "dev"
#endif

#ifdef CONFIG_SI_EMBEDDED_AGENT
#define SI_CFG_EMBEDDED_AGENT_ENABLED 1
#else
#define SI_CFG_EMBEDDED_AGENT_ENABLED 0
#endif

#ifdef CONFIG_SI_UART_TERMINAL
#define SI_CFG_UART_TERMINAL_ENABLED 1
#else
#define SI_CFG_UART_TERMINAL_ENABLED 0
#endif

#define SI_STATUS_POLL_INTERVAL_MS 1000U
#define SI_DEFAULT_HTTP_PORT 80
#define SI_STREAM_HTTP_PORT 81

#ifndef CONFIG_SI_AUTH_USERNAME
#define CONFIG_SI_AUTH_USERNAME "admin"
#endif
#ifndef CONFIG_SI_AUTH_PASSWORD
#define CONFIG_SI_AUTH_PASSWORD ""
#endif
#ifndef CONFIG_SI_VIDEO_WIDTH
#define CONFIG_SI_VIDEO_WIDTH 1920
#endif
#ifndef CONFIG_SI_VIDEO_HEIGHT
#define CONFIG_SI_VIDEO_HEIGHT 1080
#endif
#ifndef CONFIG_SI_VIDEO_UVC_FPS
#define CONFIG_SI_VIDEO_UVC_FPS 25
#endif
#ifndef CONFIG_SI_VIDEO_UVC_FRAME_BUFFERS
#define CONFIG_SI_VIDEO_UVC_FRAME_BUFFERS 3
#endif
#ifndef CONFIG_SI_VIDEO_UVC_URBS
#define CONFIG_SI_VIDEO_UVC_URBS 3
#endif
#ifndef CONFIG_SI_VIDEO_UVC_URB_SIZE
#define CONFIG_SI_VIDEO_UVC_URB_SIZE 10240
#endif
#ifndef CONFIG_SI_VIDEO_UVC_JPEG_BUFFER_SIZE
#define CONFIG_SI_VIDEO_UVC_JPEG_BUFFER_SIZE (2 * 1024 * 1024)
#endif
#ifndef CONFIG_SI_VIDEO_JPEG_QUALITY
#define CONFIG_SI_VIDEO_JPEG_QUALITY 75
#endif
#ifndef CONFIG_SI_VIDEO_STREAM_DELAY_MS
#define CONFIG_SI_VIDEO_STREAM_DELAY_MS 33
#endif
#ifndef CONFIG_SI_VIDEO_H264_BITRATE
#define CONFIG_SI_VIDEO_H264_BITRATE 8000000
#endif
#ifndef CONFIG_SI_VIDEO_H264_GOP
#define CONFIG_SI_VIDEO_H264_GOP 25
#endif
#ifndef CONFIG_SI_VIDEO_H264_MAX_ACCESS_UNIT
#define CONFIG_SI_VIDEO_H264_MAX_ACCESS_UNIT (4 * 1024 * 1024)
#endif

#define SI_CFG_AUTH_USERNAME CONFIG_SI_AUTH_USERNAME
#define SI_CFG_AUTH_PASSWORD CONFIG_SI_AUTH_PASSWORD

#ifdef CONFIG_SI_VIDEO_ENABLE
#define SI_CFG_VIDEO_ENABLED 1
#else
#define SI_CFG_VIDEO_ENABLED 0
#endif

#define SI_CFG_VIDEO_WIDTH CONFIG_SI_VIDEO_WIDTH
#define SI_CFG_VIDEO_HEIGHT CONFIG_SI_VIDEO_HEIGHT
#define SI_CFG_VIDEO_FPS CONFIG_SI_VIDEO_UVC_FPS
#define SI_CFG_VIDEO_FRAME_BUFFERS CONFIG_SI_VIDEO_UVC_FRAME_BUFFERS
#define SI_CFG_VIDEO_JPEG_BUFFER_SIZE CONFIG_SI_VIDEO_UVC_JPEG_BUFFER_SIZE
#define SI_CFG_VIDEO_JPEG_QUALITY CONFIG_SI_VIDEO_JPEG_QUALITY
#define SI_CFG_VIDEO_STREAM_DELAY_MS CONFIG_SI_VIDEO_STREAM_DELAY_MS

#ifdef CONFIG_SI_VIDEO_H264_EXPERIMENT
#define SI_CFG_VIDEO_H264_ENABLED 1
#else
#define SI_CFG_VIDEO_H264_ENABLED 0
#endif

#ifdef CONFIG_SI_VIDEO_H264_PIPELINE_OVERLAP
#define SI_CFG_VIDEO_H264_PIPELINE_OVERLAP 1
#else
#define SI_CFG_VIDEO_H264_PIPELINE_OVERLAP 0
#endif

/* UVC capture is the Stable video baseline. Optional output codecs consume
 * frames downstream and must never silently select a different USB transfer
 * topology. */
#define SI_CFG_VIDEO_URBS CONFIG_SI_VIDEO_UVC_URBS
#define SI_CFG_VIDEO_URB_SIZE CONFIG_SI_VIDEO_UVC_URB_SIZE

#define SI_CFG_VIDEO_H264_BITRATE CONFIG_SI_VIDEO_H264_BITRATE
#define SI_CFG_VIDEO_H264_GOP CONFIG_SI_VIDEO_H264_GOP
#define SI_CFG_VIDEO_H264_HIGH_RES_MAX_FPS 25U
#define SI_CFG_VIDEO_H264_720P_MAX_FPS 30U
#define SI_CFG_VIDEO_H264_MAX_ACCESS_UNIT CONFIG_SI_VIDEO_H264_MAX_ACCESS_UNIT

static inline bool si_auth_enabled(void)
{
    return SI_CFG_AUTH_PASSWORD[0] != '\0';
}
