#pragma once

/*
 * Single compile-time view of the selected hardware profile.
 *
 * Board values are declared in Kconfig.projbuild and selected by an
 * sdkconfig.defaults profile. Drivers include this header instead of reading
 * CONFIG_* symbols or carrying private fallback GPIO values.
 */

#include "sdkconfig.h"
#include "esp_idf_version.h"

#define SI_BOARD_ID CONFIG_SI_BOARD_ID
#define SI_BOARD_NAME CONFIG_SI_BOARD_NAME
#define SI_BOARD_HOSTNAME CONFIG_SI_BOARD_HOSTNAME
#define SI_SILICON_TARGET CONFIG_SI_SILICON_TARGET
#define SI_CFG_ETH_PHY_NAME CONFIG_SI_ETH_PHY_NAME
#define SI_CFG_ETH_DRIVER_NAME CONFIG_SI_ETH_DRIVER_NAME

#if defined(CONFIG_SI_BOARD_REQUIRES_REV3) && defined(CONFIG_ESP32P4_SELECTS_REV_LESS_V3)
#error "The selected ExoAnchor prototype requires the esp32p4-rev3 silicon overlay"
#endif

#if defined(CONFIG_SI_BOARD_REQUIRES_REV3) && ESP_IDF_VERSION < ESP_IDF_VERSION_VAL(5, 5, 5)
#error "ESP32-P4 rev3 prototype profiles require ESP-IDF v5.5.5 or newer"
#endif

/* Disabled Kconfig menus may omit their dependent symbols from sdkconfig.h. */
#ifndef CONFIG_SI_ETH_MDC_GPIO
#define CONFIG_SI_ETH_MDC_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_MDIO_GPIO
#define CONFIG_SI_ETH_MDIO_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_PHY_RST_GPIO
#define CONFIG_SI_ETH_PHY_RST_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_PHY_ADDR
#define CONFIG_SI_ETH_PHY_ADDR -1
#endif
#ifndef CONFIG_SI_ETH_RMII_CLK_GPIO
#define CONFIG_SI_ETH_RMII_CLK_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_RMII_TX_EN_GPIO
#define CONFIG_SI_ETH_RMII_TX_EN_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_RMII_TXD0_GPIO
#define CONFIG_SI_ETH_RMII_TXD0_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_RMII_TXD1_GPIO
#define CONFIG_SI_ETH_RMII_TXD1_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_RMII_CRS_DV_GPIO
#define CONFIG_SI_ETH_RMII_CRS_DV_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_RMII_RXD0_GPIO
#define CONFIG_SI_ETH_RMII_RXD0_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_RMII_RXD1_GPIO
#define CONFIG_SI_ETH_RMII_RXD1_GPIO -1
#endif
#ifndef CONFIG_SI_ETH_WAIT_IP_TIMEOUT_MS
#define CONFIG_SI_ETH_WAIT_IP_TIMEOUT_MS 0
#endif
#ifndef CONFIG_SI_MS2109_EEPROM_WP_GPIO
#define CONFIG_SI_MS2109_EEPROM_WP_GPIO -1
#endif
#ifndef CONFIG_SI_MS2109_EEPROM_SCL_GPIO
#define CONFIG_SI_MS2109_EEPROM_SCL_GPIO -1
#endif
#ifndef CONFIG_SI_MS2109_EEPROM_SDA_GPIO
#define CONFIG_SI_MS2109_EEPROM_SDA_GPIO -1
#endif
#ifndef CONFIG_SI_MS2109_SWITCH_GPIO
#define CONFIG_SI_MS2109_SWITCH_GPIO -1
#endif
#ifndef CONFIG_SI_MS2109_CORE_ENABLE_GPIO
#define CONFIG_SI_MS2109_CORE_ENABLE_GPIO -1
#endif
#ifndef CONFIG_SI_MS2109_POWER_SEQUENCE_DELAY_MS
#define CONFIG_SI_MS2109_POWER_SEQUENCE_DELAY_MS 10
#endif

#ifdef CONFIG_SI_ETH_ENABLE
#define SI_CFG_ETH_ENABLED 1
#else
#define SI_CFG_ETH_ENABLED 0
#endif

#define SI_CFG_ETH_MDC_GPIO CONFIG_SI_ETH_MDC_GPIO
#define SI_CFG_ETH_MDIO_GPIO CONFIG_SI_ETH_MDIO_GPIO
#define SI_CFG_ETH_PHY_RESET_GPIO CONFIG_SI_ETH_PHY_RST_GPIO
#define SI_CFG_ETH_PHY_ADDRESS CONFIG_SI_ETH_PHY_ADDR
#define SI_CFG_ETH_RMII_CLOCK_GPIO CONFIG_SI_ETH_RMII_CLK_GPIO
#define SI_CFG_ETH_RMII_TX_ENABLE_GPIO CONFIG_SI_ETH_RMII_TX_EN_GPIO
#define SI_CFG_ETH_RMII_TXD0_GPIO CONFIG_SI_ETH_RMII_TXD0_GPIO
#define SI_CFG_ETH_RMII_TXD1_GPIO CONFIG_SI_ETH_RMII_TXD1_GPIO
#define SI_CFG_ETH_RMII_CRS_DV_GPIO CONFIG_SI_ETH_RMII_CRS_DV_GPIO
#define SI_CFG_ETH_RMII_RXD0_GPIO CONFIG_SI_ETH_RMII_RXD0_GPIO
#define SI_CFG_ETH_RMII_RXD1_GPIO CONFIG_SI_ETH_RMII_RXD1_GPIO
#define SI_CFG_ETH_WAIT_IP_TIMEOUT_MS CONFIG_SI_ETH_WAIT_IP_TIMEOUT_MS
#define SI_CFG_MS2109_EEPROM_WP_GPIO CONFIG_SI_MS2109_EEPROM_WP_GPIO
#ifdef CONFIG_SI_MS2109_EEPROM_EMULATOR_ENABLE
#define SI_CFG_MS2109_EEPROM_EMULATOR_ENABLED 1
#else
#define SI_CFG_MS2109_EEPROM_EMULATOR_ENABLED 0
#endif
#define SI_CFG_MS2109_EEPROM_SCL_GPIO CONFIG_SI_MS2109_EEPROM_SCL_GPIO
#define SI_CFG_MS2109_EEPROM_SDA_GPIO CONFIG_SI_MS2109_EEPROM_SDA_GPIO
#ifdef CONFIG_SI_MS2109_TEST_ENABLE
#define SI_CFG_MS2109_TEST_ENABLED 1
#else
#define SI_CFG_MS2109_TEST_ENABLED 0
#endif
#ifdef CONFIG_SI_MS2109_POWER_ENABLE
#define SI_CFG_MS2109_POWER_ENABLED 1
#else
#define SI_CFG_MS2109_POWER_ENABLED 0
#endif
#define SI_CFG_MS2109_SWITCH_GPIO CONFIG_SI_MS2109_SWITCH_GPIO
#ifdef CONFIG_SI_MS2109_SWITCH_ACTIVE_HIGH
#define SI_CFG_MS2109_SWITCH_ACTIVE_HIGH 1
#else
#define SI_CFG_MS2109_SWITCH_ACTIVE_HIGH 0
#endif
#define SI_CFG_MS2109_CORE_ENABLE_GPIO CONFIG_SI_MS2109_CORE_ENABLE_GPIO
#ifdef CONFIG_SI_MS2109_CORE_ENABLE_ACTIVE_HIGH
#define SI_CFG_MS2109_CORE_ENABLE_ACTIVE_HIGH 1
#else
#define SI_CFG_MS2109_CORE_ENABLE_ACTIVE_HIGH 0
#endif
#define SI_CFG_MS2109_POWER_SEQUENCE_DELAY_MS \
    CONFIG_SI_MS2109_POWER_SEQUENCE_DELAY_MS

#if SI_CFG_MS2109_POWER_ENABLED && SI_CFG_MS2109_TEST_ENABLED
#error "Product MS2109 power control and destructive MS2109 test cannot both be enabled"
#endif

#ifndef CONFIG_SI_POWER_BUTTON_GPIO
#define CONFIG_SI_POWER_BUTTON_GPIO -1
#endif
#ifndef CONFIG_SI_RESET_BUTTON_GPIO
#define CONFIG_SI_RESET_BUTTON_GPIO -1
#endif
#ifndef CONFIG_SI_POWER_PRESS_MS
#define CONFIG_SI_POWER_PRESS_MS 500
#endif
#ifndef CONFIG_SI_POWER_FORCE_OFF_MS
#define CONFIG_SI_POWER_FORCE_OFF_MS 5000
#endif
#ifndef CONFIG_SI_POWER_DETECT_GPIO
#define CONFIG_SI_POWER_DETECT_GPIO -1
#endif
#ifndef CONFIG_SI_STANDBY_DETECT_GPIO
#define CONFIG_SI_STANDBY_DETECT_GPIO -1
#endif
#ifndef CONFIG_SI_POWER_LOCATOR_GPIO
#define CONFIG_SI_POWER_LOCATOR_GPIO -1
#endif
#ifndef CONFIG_SI_POWER_LOCATOR_RETURN_GPIO
#define CONFIG_SI_POWER_LOCATOR_RETURN_GPIO -1
#endif

#ifdef CONFIG_SI_POWER_ENABLE
#define SI_CFG_POWER_ENABLED 1
#else
#define SI_CFG_POWER_ENABLED 0
#endif

#define SI_CFG_POWER_BUTTON_GPIO CONFIG_SI_POWER_BUTTON_GPIO
#define SI_CFG_RESET_BUTTON_GPIO CONFIG_SI_RESET_BUTTON_GPIO
#ifdef CONFIG_SI_POWER_ACTIVE_HIGH
#define SI_CFG_POWER_ACTIVE_HIGH 1
#else
#define SI_CFG_POWER_ACTIVE_HIGH 0
#endif
#define SI_CFG_POWER_PRESS_MS CONFIG_SI_POWER_PRESS_MS
#define SI_CFG_POWER_FORCE_OFF_MS CONFIG_SI_POWER_FORCE_OFF_MS
#define SI_CFG_POWER_DETECT_GPIO CONFIG_SI_POWER_DETECT_GPIO
#ifdef CONFIG_SI_POWER_DETECT_ACTIVE_HIGH
#define SI_CFG_POWER_DETECT_ACTIVE_HIGH 1
#else
#define SI_CFG_POWER_DETECT_ACTIVE_HIGH 0
#endif
#define SI_CFG_STANDBY_DETECT_GPIO CONFIG_SI_STANDBY_DETECT_GPIO
#ifdef CONFIG_SI_STANDBY_DETECT_ACTIVE_HIGH
#define SI_CFG_STANDBY_DETECT_ACTIVE_HIGH 1
#else
#define SI_CFG_STANDBY_DETECT_ACTIVE_HIGH 0
#endif
#define SI_CFG_POWER_LOCATOR_GPIO CONFIG_SI_POWER_LOCATOR_GPIO
#define SI_CFG_POWER_LOCATOR_RETURN_GPIO CONFIG_SI_POWER_LOCATOR_RETURN_GPIO
#ifdef CONFIG_SI_POWER_LOCATOR_ACTIVE_HIGH
#define SI_CFG_POWER_LOCATOR_ACTIVE_HIGH 1
#else
#define SI_CFG_POWER_LOCATOR_ACTIVE_HIGH 0
#endif

#ifndef CONFIG_SI_HID_USB_DM_GPIO
#define CONFIG_SI_HID_USB_DM_GPIO -1
#endif
#ifndef CONFIG_SI_HID_USB_DP_GPIO
#define CONFIG_SI_HID_USB_DP_GPIO -1
#endif
#ifndef CONFIG_SI_HID_USB_MANUFACTURER
#define CONFIG_SI_HID_USB_MANUFACTURER "ExoAnchor"
#endif
#ifndef CONFIG_SI_HID_USB_PRODUCT
#define CONFIG_SI_HID_USB_PRODUCT "ESP32-P4 USB HID"
#endif
#ifndef CONFIG_SI_HID_USB_SERIAL
#define CONFIG_SI_HID_USB_SERIAL "P4-FS-HID"
#endif

#ifdef CONFIG_SI_HID_USB_ENABLE
#define SI_CFG_HID_ENABLED 1
#else
#define SI_CFG_HID_ENABLED 0
#endif

#define SI_CFG_HID_DM_GPIO CONFIG_SI_HID_USB_DM_GPIO
#define SI_CFG_HID_DP_GPIO CONFIG_SI_HID_USB_DP_GPIO
#define SI_CFG_HID_MANUFACTURER CONFIG_SI_HID_USB_MANUFACTURER
#define SI_CFG_HID_PRODUCT CONFIG_SI_HID_USB_PRODUCT
#define SI_CFG_HID_SERIAL CONFIG_SI_HID_USB_SERIAL

#define SI_CFG_TF_CARD_DETECT_GPIO CONFIG_SI_TF_CARD_DETECT_GPIO
#define SI_CFG_TF_SDMMC_CLK_GPIO CONFIG_SI_TF_SDMMC_CLK_GPIO
#define SI_CFG_TF_SDMMC_CMD_GPIO CONFIG_SI_TF_SDMMC_CMD_GPIO
#define SI_CFG_TF_SDMMC_D0_GPIO CONFIG_SI_TF_SDMMC_D0_GPIO
#define SI_CFG_TF_SDMMC_D1_GPIO CONFIG_SI_TF_SDMMC_D1_GPIO
#define SI_CFG_TF_SDMMC_D2_GPIO CONFIG_SI_TF_SDMMC_D2_GPIO
#define SI_CFG_TF_SDMMC_D3_GPIO CONFIG_SI_TF_SDMMC_D3_GPIO
#define SI_CFG_TF_SDMMC_BUS_WIDTH CONFIG_SI_TF_SDMMC_BUS_WIDTH
#ifdef CONFIG_SI_TF_SDMMC_LOW_SPEED_FALLBACK
#define SI_CFG_TF_SDMMC_LOW_SPEED_FALLBACK 1
#else
#define SI_CFG_TF_SDMMC_LOW_SPEED_FALLBACK 0
#endif
#ifndef CONFIG_SI_TF_SDMMC_LOW_SPEED_FREQ_KHZ
#define CONFIG_SI_TF_SDMMC_LOW_SPEED_FREQ_KHZ 10000
#endif
#define SI_CFG_TF_SDMMC_LOW_SPEED_FREQ_KHZ CONFIG_SI_TF_SDMMC_LOW_SPEED_FREQ_KHZ
#define SI_CFG_TF_LDO_CHANNEL CONFIG_SI_TF_LDO_CHANNEL

#ifndef CONFIG_SI_TARGET_UART_PORT
#define CONFIG_SI_TARGET_UART_PORT 1
#endif
#ifndef CONFIG_SI_TARGET_UART_RX_GPIO
#define CONFIG_SI_TARGET_UART_RX_GPIO -1
#endif
#ifndef CONFIG_SI_TARGET_UART_TX_GPIO
#define CONFIG_SI_TARGET_UART_TX_GPIO -1
#endif
#ifndef CONFIG_SI_TARGET_UART_BAUD_RATE
#define CONFIG_SI_TARGET_UART_BAUD_RATE 115200
#endif
#ifndef CONFIG_SI_TARGET_UART_FALLBACK_BAUD_RATE
#define CONFIG_SI_TARGET_UART_FALLBACK_BAUD_RATE 9600
#endif

#ifdef CONFIG_SI_TARGET_UART_ENABLE
#define SI_CFG_TARGET_UART_ENABLED 1
#else
#define SI_CFG_TARGET_UART_ENABLED 0
#endif

#define SI_CFG_TARGET_UART_PORT CONFIG_SI_TARGET_UART_PORT
#define SI_CFG_TARGET_UART_RX_GPIO CONFIG_SI_TARGET_UART_RX_GPIO
#define SI_CFG_TARGET_UART_TX_GPIO CONFIG_SI_TARGET_UART_TX_GPIO
#define SI_CFG_TARGET_UART_BAUD_RATE CONFIG_SI_TARGET_UART_BAUD_RATE
#define SI_CFG_TARGET_UART_FALLBACK_BAUD_RATE \
    CONFIG_SI_TARGET_UART_FALLBACK_BAUD_RATE
