#pragma once

/* Persistent filesystem layout. Change paths here, not in drivers/services. */

#define SI_TF_MOUNT_POINT "/sdcard"
#define SI_STORAGE_ROOT SI_TF_MOUNT_POINT "/EA"
#define SI_STORAGE_ASSETS_DIR SI_STORAGE_ROOT "/ASSETS"
#define SI_STORAGE_AGENT_DIR SI_STORAGE_ROOT "/AGENT"
#define SI_STORAGE_LOGS_DIR SI_STORAGE_ROOT "/LOGS"
#define SI_STORAGE_SNAPSHOTS_DIR SI_STORAGE_ROOT "/SNAPSHOTS"
#define SI_STORAGE_EXPORTS_DIR SI_STORAGE_ROOT "/EXPORTS"
#define SI_STORAGE_MCP_DIR SI_STORAGE_ROOT "/MCP"
#define SI_STORAGE_OTA_DIR SI_STORAGE_ROOT "/OTA"
